### ISSUE TITLE
Card Pop-Up Web Component

### ISSUE THREAD

**Issue by Sholehani** [cse110-sp23-group24/cse110-sp23-group24-Final-Project#30]
# Task: Develop web component for selected cards

- [x] Card fill majority/entire screen
- [x] Display image and title
- [ ] Option to exit on the top right of the screen
- [x] Do a card flip animation when the card is interacted with
- [ ] Merge with main

**Comment by Sholehani** [comment]
Progress (6/2)

Added the display card zoom-in and fade-out after card selection.

Issues: 
- Could not enlarge the front card to fill the entire screen during card flip. The flexbox component does not allow its child component to overlap the box border.
- Consult with the team to keep the current animation instead.
